// Copyright Epic Games, Inc. All Rights Reserved.
#include "IdolQuizWidget.h"
#include "../Audio/UiSoundStyle.h"
#include "Blueprint/WidgetTree.h"
#include "Components/Button.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/EditableTextBox.h"
#include "Components/Image.h"
#include "Components/HorizontalBox.h"
#include "Components/HorizontalBoxSlot.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/VerticalBoxSlot.h"
#include "Kismet/GameplayStatics.h"
#include "../Core/IdolQuizGameModeBase.h"
#include "../Core/IdolQuizGameStateBase.h"
#include "../Core/IdolQuizPlayerController.h"
#include "../Core/IdolQuizPlayerState.h"
#include "../Core/RhythmAccountSubsystem.h"
#include "QuizPlayerColors.h"
namespace{constexpr double ChatMessageLifetimeSeconds=3.0;UTextBlock* QuizText(UWidgetTree* Tree,const TCHAR* Name,const FString& Value,int32 Size){UTextBlock* Text=Tree->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(),Name);Text->SetText(FText::FromString(Value));Text->SetJustification(ETextJustify::Center);Text->SetColorAndOpacity(FSlateColor(FLinearColor::White));FSlateFontInfo Font=Text->GetFont();Font.Size=Size;Text->SetFont(Font);return Text;}}
UIdolQuizWidget::UIdolQuizWidget(const FObjectInitializer& ObjectInitializer):Super(ObjectInitializer){SetIsFocusable(true);}
TSharedRef<SWidget> UIdolQuizWidget::RebuildWidget(){if(WidgetTree&&!WidgetTree->RootWidget)BuildLayout();return Super::RebuildWidget();}
void UIdolQuizWidget::BuildLayout()
{
	UCanvasPanel* Root=WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(),TEXT("IdolQuizRoot"));WidgetTree->RootWidget=Root;
	auto Add=[Root](UWidget* Widget,float X,float Y,FVector2D Size){UCanvasPanelSlot* CanvasSlot=Root->AddChildToCanvas(Widget);CanvasSlot->SetAnchors(FAnchors(X,Y));CanvasSlot->SetAlignment(FVector2D(.5f,.5f));CanvasSlot->SetSize(Size);};
	UImage* Background=WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(),TEXT("Background"));Background->SetColorAndOpacity(FLinearColor(.006f,.012f,.035f,1));UCanvasPanelSlot* BackgroundSlot=Root->AddChildToCanvas(Background);BackgroundSlot->SetAnchors(FAnchors(0,0,1,1));BackgroundSlot->SetOffsets(FMargin(0));
	for(int32 Index=0;Index<6;++Index){const int32 Column=Index%3;const int32 Row=Index/3;const float X=.075f+Column*.145f;const float Y=.04f+Row*.045f;UTextBlock* Name=QuizText(WidgetTree,*FString::Printf(TEXT("PlayerName%d"),Index+1),TEXT("None"),16);Name->SetColorAndOpacity(FSlateColor(QuizPlayerColors::Get(Index)));Name->SetJustification(ETextJustify::Left);Add(Name,X,Y,FVector2D(165,34));PlayerNameTexts.Add(Name);UTextBlock* Count=QuizText(WidgetTree,*FString::Printf(TEXT("PlayerCount%d"),Index+1),TEXT("0"),16);Count->SetColorAndOpacity(FSlateColor(FLinearColor::White));Add(Count,X+.052f,Y,FVector2D(45,34));PlayerCountTexts.Add(Count);}
	TimerText=QuizText(WidgetTree,TEXT("TimerText"),TEXT("TIME 30"),34);Add(TimerText,.5f,.06f,FVector2D(280,60));
	RoundText=QuizText(WidgetTree,TEXT("RoundText"),TEXT("1 / 10"),20);Add(RoundText,.76f,.075f,FVector2D(240,44));
	SkipText=QuizText(WidgetTree,TEXT("SkipText"),TEXT("스킵 : K (0/1)"),20);SkipText->SetColorAndOpacity(FSlateColor(FLinearColor(.75f,.85f,1.f)));Add(SkipText,.88f,.075f,FVector2D(260,44));
	UImage* ChatBackground=WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(),TEXT("ChatBackground"));ChatBackground->SetColorAndOpacity(FLinearColor(.015f,.03f,.08f,.88f));Add(ChatBackground,.27f,.48f,FVector2D(860,650));
	ChatContainer=WidgetTree->ConstructWidget<UVerticalBox>(UVerticalBox::StaticClass(),TEXT("ChatContainer"));Add(ChatContainer,.27f,.48f,FVector2D(810,600));
	FaceImage=WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(),TEXT("FaceImage"));Add(FaceImage,.75f,.49f,FVector2D(720,720));
	FeedbackText=QuizText(WidgetTree,TEXT("FeedbackText"),TEXT(""),28);Add(FeedbackText,.75f,.14f,FVector2D(650,55));
	HintText=QuizText(WidgetTree,TEXT("HintText"),TEXT(""),28);HintText->SetColorAndOpacity(FSlateColor(FLinearColor(1.f,.85f,.25f)));Add(HintText,.75f,.87f,FVector2D(650,50));
	AnswerInput=WidgetTree->ConstructWidget<UEditableTextBox>(UEditableTextBox::StaticClass(),TEXT("AnswerInput"));AnswerInput->SetHintText(FText::FromString(TEXT("채팅 또는 정답 입력")));FEditableTextBoxStyle AnswerStyle=AnswerInput->GetWidgetStyle();const FSlateColor BlackText(FLinearColor::Black);AnswerStyle.SetForegroundColor(BlackText).SetFocusedForegroundColor(BlackText).SetReadOnlyForegroundColor(BlackText);FTextBlockStyle InputTextStyle=AnswerStyle.TextStyle;InputTextStyle.SetColorAndOpacity(BlackText);AnswerStyle.SetTextStyle(InputTextStyle);AnswerInput->SetWidgetStyle(AnswerStyle);AnswerInput->OnTextCommitted.AddDynamic(this,&ThisClass::HandleTextCommitted);Add(AnswerInput,.23f,.88f,FVector2D(680,58));
	SubmitButton=WidgetTree->ConstructWidget<UButton>(UButton::StaticClass(),TEXT("SubmitButton"));SubmitButton->AddChild(QuizText(WidgetTree,TEXT("SubmitText"),TEXT("전송"),24));SubmitButton->OnClicked.AddDynamic(this,&ThisClass::HandleSubmit);Add(SubmitButton,.46f,.88f,FVector2D(150,58));
	RestartButton=WidgetTree->ConstructWidget<UButton>(UButton::StaticClass(),TEXT("RestartButton"));RestartButton->AddChild(QuizText(WidgetTree,TEXT("RestartText"),TEXT("다시 하기"),24));RestartButton->OnClicked.AddDynamic(this,&ThisClass::HandleRestart);Add(RestartButton,.27f,.88f,FVector2D(230,62));RestartButton->SetVisibility(ESlateVisibility::Collapsed);
	UButton* HubButton=WidgetTree->ConstructWidget<UButton>(UButton::StaticClass(),TEXT("HubButton"));HubButton->AddChild(QuizText(WidgetTree,TEXT("HubText"),TEXT("ALL GAMES"),20));HubButton->OnClicked.AddDynamic(this,&ThisClass::HandleMainHub);Add(HubButton,.92f,.95f,FVector2D(170,48));
}
void UIdolQuizWidget::NativeConstruct(){Super::NativeConstruct();if(UGameInstance* GameInstance=GetGameInstance())if(URhythmAccountSubsystem* Accounts=GameInstance->GetSubsystem<URhythmAccountSubsystem>())if(!Accounts->GetUsername().IsEmpty())LocalPlayerName=Accounts->GetUsername();RefreshPlayerSlots();BindGameState();CloseChatInput();AllGamesUiSound::ApplyButtonClickSound(WidgetTree);}
void UIdolQuizWidget::NativeTick(const FGeometry& MyGeometry,float InDeltaTime){Super::NativeTick(MyGeometry,InDeltaTime);if(!QuizGameState)BindGameState();RefreshPlayerSlots();const double Now=FPlatformTime::Seconds();for(int32 Index=ChatMessages.Num()-1;Index>=0;--Index)if(ChatMessages[Index].ExpiresAtSeconds<=Now){if(ChatMessages[Index].Row)ChatMessages[Index].Row->RemoveFromParent();ChatMessages.RemoveAt(Index);}}
FReply UIdolQuizWidget::NativeOnKeyDown(const FGeometry& InGeometry,const FKeyEvent& InKeyEvent){if(InKeyEvent.GetKey()==EKeys::Enter){if(!bChatInputOpen)OpenChatInput();else if(AnswerInput&&AnswerInput->GetText().IsEmpty())CloseChatInput();return FReply::Handled();}if(InKeyEvent.GetKey()==EKeys::K&&!bChatInputOpen){if(AIdolQuizPlayerController* PC=GetOwningPlayer<AIdolQuizPlayerController>())PC->ServerRequestSkip();return FReply::Handled();}return Super::NativeOnKeyDown(InGeometry,InKeyEvent);}
void UIdolQuizWidget::BindGameState(){AIdolQuizGameStateBase* State=GetWorld()?GetWorld()->GetGameState<AIdolQuizGameStateBase>():nullptr;if(!State||State==QuizGameState)return;QuizGameState=State;QuizGameState->OnQuizStateChanged.AddUObject(this,&ThisClass::RefreshReplicatedState);QuizGameState->OnChatReceived.AddUObject(this,&ThisClass::HandleNetworkChat);QuizGameState->OnFeedbackReceived.AddUObject(this,&ThisClass::HandleNetworkFeedback);QuizGameState->OnSkipReceived.AddUObject(this,&ThisClass::HandleNetworkSkip);RefreshReplicatedState();}
void UIdolQuizWidget::NativeDestruct(){if(QuizGameState){QuizGameState->OnQuizStateChanged.RemoveAll(this);QuizGameState->OnChatReceived.RemoveAll(this);QuizGameState->OnFeedbackReceived.RemoveAll(this);QuizGameState->OnSkipReceived.RemoveAll(this);}Super::NativeDestruct();}
void UIdolQuizWidget::RefreshReplicatedState(){if(!QuizGameState)return;if(QuizGameState->IsFinished()){HandleQuizFinished(0,QuizGameState->GetTotalRounds());return;}if(QuizGameState->GetRound()!=LastDisplayedRound){LastDisplayedRound=QuizGameState->GetRound();FeedbackText->SetText(FText::GetEmpty());if(AnswerInput)AnswerInput->SetText(FText::GetEmpty());}if(QuizGameState->GetQuestionImagePath().IsValid()){UTexture2D* Texture=Cast<UTexture2D>(QuizGameState->GetQuestionImagePath().TryLoad());FaceImage->SetBrushFromTexture(Texture,true);FaceImage->SetVisibility(Texture?ESlateVisibility::Visible:ESlateVisibility::Collapsed);}RoundText->SetText(FText::FromString(FString::Printf(TEXT("%d / %d"),QuizGameState->GetRound(),QuizGameState->GetTotalRounds())));SkipText->SetText(FText::FromString(FString::Printf(TEXT("스킵 : K (%d/%d)"),QuizGameState->GetSkipVotes(),QuizGameState->GetRequiredSkipVotes())));HandleTimeChanged(QuizGameState->GetRemainingTime());HandleHintChanged(QuizGameState->GetHint());}
void UIdolQuizWidget::HandleNetworkChat(const FString& PlayerName,const FString& Message,const int32 PlayerColorIndex){AddChatMessage(PlayerName,Message,PlayerColorIndex);}
void UIdolQuizWidget::HandleNetworkFeedback(bool bCorrect,const FString& PlayerName,const FString& Message){if(bCorrect){FeedbackText->SetColorAndOpacity(FSlateColor(FLinearColor(.3f,1,.5f)));FeedbackText->SetText(FText::FromString(FString::Printf(TEXT("%s 정답! %s"),*PlayerName,*Message)));}else HandleRoundTimedOut(Message);}
void UIdolQuizWidget::HandleNetworkSkip(const FString& CorrectAnswer){FeedbackText->SetColorAndOpacity(FSlateColor(FLinearColor(.35f,.75f,1.f)));FeedbackText->SetText(FText::FromString(FString::Printf(TEXT("스킵! 정답: %s"),*CorrectAnswer)));if(AnswerInput)AnswerInput->SetText(FText::GetEmpty());}
void UIdolQuizWidget::HandleQuestionChanged(const FIdolQuizQuestion& Question,int32 Round,int32 Total){FaceImage->SetBrushFromTexture(Question.Image.LoadSynchronous(),true);FaceImage->SetVisibility(ESlateVisibility::Visible);RoundText->SetText(FText::FromString(FString::Printf(TEXT("%d / %d"),Round,Total)));FeedbackText->SetText(FText::GetEmpty());if(AnswerInput)AnswerInput->SetText(FText::GetEmpty());CloseChatInput();}
void UIdolQuizWidget::HandleAnswerResolved(bool bCorrect,const FString& Answer,int32 Score){if(bCorrect){FeedbackText->SetColorAndOpacity(FSlateColor(FLinearColor(.3f,1,.5f)));FeedbackText->SetText(FText::FromString(FString::Printf(TEXT("정답! %s"),*Answer)));RefreshPlayerSlots(Score/100);}if(AnswerInput)AnswerInput->SetText(FText::GetEmpty());}
void UIdolQuizWidget::AddChatMessage(const FString& PlayerName,const FString& Message,const int32 PlayerColorIndex){if(Message.IsEmpty()||!ChatContainer)return;const int32 MessageId=NextChatMessageId++;UHorizontalBox* Row=WidgetTree->ConstructWidget<UHorizontalBox>(UHorizontalBox::StaticClass(),*FString::Printf(TEXT("ChatRow%d"),MessageId));UTextBlock* NameText=QuizText(WidgetTree,*FString::Printf(TEXT("ChatName%d"),MessageId),FString::Printf(TEXT("%s: "),*PlayerName),22);NameText->SetJustification(ETextJustify::Left);NameText->SetColorAndOpacity(FSlateColor(QuizPlayerColors::Get(PlayerColorIndex)));if(UHorizontalBoxSlot* NameSlot=Row->AddChildToHorizontalBox(NameText))NameSlot->SetSize(FSlateChildSize(ESlateSizeRule::Automatic));UTextBlock* MessageText=QuizText(WidgetTree,*FString::Printf(TEXT("ChatMessage%d"),MessageId),Message,22);MessageText->SetJustification(ETextJustify::Left);MessageText->SetAutoWrapText(true);if(UHorizontalBoxSlot* MessageSlot=Row->AddChildToHorizontalBox(MessageText))MessageSlot->SetSize(FSlateChildSize(ESlateSizeRule::Fill));if(UVerticalBoxSlot* RowSlot=ChatContainer->AddChildToVerticalBox(Row))RowSlot->SetPadding(FMargin(0,2));ChatMessages.Add({Row,FPlatformTime::Seconds()+ChatMessageLifetimeSeconds});constexpr int32 MaxVisibleMessages=12;while(ChatMessages.Num()>MaxVisibleMessages){if(ChatMessages[0].Row)ChatMessages[0].Row->RemoveFromParent();ChatMessages.RemoveAt(0);}}
void UIdolQuizWidget::RefreshPlayerSlots(int32){for(int32 Index=0;Index<6;++Index){if(PlayerNameTexts.IsValidIndex(Index)){PlayerNameTexts[Index]->SetText(FText::FromString(TEXT("None")));PlayerNameTexts[Index]->SetColorAndOpacity(FSlateColor(QuizPlayerColors::Get(Index)));}if(PlayerCountTexts.IsValidIndex(Index))PlayerCountTexts[Index]->SetText(FText::AsNumber(0));}if(GetWorld()&&GetWorld()->GetGameState())for(APlayerState* BasePlayerState:GetWorld()->GetGameState()->PlayerArray)if(const AIdolQuizPlayerState* PS=Cast<AIdolQuizPlayerState>(BasePlayerState)){const int32 Index=FMath::Clamp(PS->GetPlayerColorIndex(),0,5);if(PlayerNameTexts.IsValidIndex(Index))PlayerNameTexts[Index]->SetText(FText::FromString(PS->GetQuizPlayerName()));if(PlayerCountTexts.IsValidIndex(Index))PlayerCountTexts[Index]->SetText(FText::AsNumber(PS->GetCorrectAnswers()));}}
void UIdolQuizWidget::OpenChatInput(){bChatInputOpen=true;if(AnswerInput){AnswerInput->SetVisibility(ESlateVisibility::Visible);AnswerInput->SetText(FText::GetEmpty());AnswerInput->SetKeyboardFocus();}if(SubmitButton)SubmitButton->SetVisibility(ESlateVisibility::Visible);}
void UIdolQuizWidget::CloseChatInput(){bChatInputOpen=false;if(AnswerInput){AnswerInput->SetText(FText::GetEmpty());AnswerInput->SetVisibility(ESlateVisibility::Collapsed);}if(SubmitButton)SubmitButton->SetVisibility(ESlateVisibility::Collapsed);SetKeyboardFocus();}
void UIdolQuizWidget::HandleTimeChanged(int32 RemainingSeconds){TimerText->SetText(FText::FromString(FString::Printf(TEXT("TIME %02d"),RemainingSeconds)));TimerText->SetColorAndOpacity(FSlateColor(RemainingSeconds<=5?FLinearColor(1.f,.2f,.2f):FLinearColor(.25f,.9f,1.f)));}
void UIdolQuizWidget::HandleHintChanged(const FString& Hint){HintText->SetText(Hint.IsEmpty()?FText::GetEmpty():FText::FromString(FString::Printf(TEXT("힌트  %s"),*Hint)));}
void UIdolQuizWidget::HandleRoundTimedOut(const FString& CorrectAnswer){FeedbackText->SetColorAndOpacity(FSlateColor(FLinearColor(1.f,.25f,.25f)));FeedbackText->SetText(FText::FromString(FString::Printf(TEXT("시간 초과! 정답: %s"),*CorrectAnswer)));AnswerInput->SetText(FText::GetEmpty());}
void UIdolQuizWidget::HandleQuizFinished(int32 Score,int32 Total){FaceImage->SetVisibility(ESlateVisibility::Collapsed);FeedbackText->SetText(FText::FromString(FString::Printf(TEXT("게임 종료! %d점 / %d문제"),Score,Total)));AnswerInput->SetVisibility(ESlateVisibility::Collapsed);SubmitButton->SetVisibility(ESlateVisibility::Collapsed);RestartButton->SetVisibility(ESlateVisibility::Visible);}
void UIdolQuizWidget::HandleSubmit(){if(!AnswerInput)return;const FString Message=AnswerInput->GetText().ToString().TrimStartAndEnd();if(!Message.IsEmpty())if(AIdolQuizPlayerController* PC=GetOwningPlayer<AIdolQuizPlayerController>())PC->ServerSubmitQuizMessage(Message);CloseChatInput();}
void UIdolQuizWidget::HandleTextCommitted(const FText&,ETextCommit::Type Method){if(Method==ETextCommit::OnEnter)HandleSubmit();}
void UIdolQuizWidget::HandleRestart(){UGameplayStatics::OpenLevel(this,TEXT("IdolQuizMap"));}
void UIdolQuizWidget::HandleMainHub(){UGameplayStatics::OpenLevel(this,TEXT("MainHubMap"));}
