#include "IdolQuizRoomWidget.h"
#include "Blueprint/WidgetTree.h"
#include "Components/Button.h"
#include "Components/CanvasPanel.h"
#include "Components/CanvasPanelSlot.h"
#include "Components/ComboBoxString.h"
#include "Components/EditableTextBox.h"
#include "Components/Image.h"
#include "Components/TextBlock.h"
#include "Kismet/GameplayStatics.h"
namespace{UTextBlock* Txt(UWidgetTree* T,const TCHAR* N,const FString& V,int32 S){UTextBlock* W=T->ConstructWidget<UTextBlock>(UTextBlock::StaticClass(),N);W->SetText(FText::FromString(V));W->SetJustification(ETextJustify::Center);FSlateFontInfo F=W->GetFont();F.Size=S;W->SetFont(F);return W;}UButton* Btn(UWidgetTree* T,const TCHAR* N,const FString& V,int32 S){UButton* B=T->ConstructWidget<UButton>(UButton::StaticClass(),N);B->AddChild(Txt(T,*FString(N).Append(TEXT("Text")),V,S));return B;}void BlackInput(UEditableTextBox* I){const FSlateColor Black(FLinearColor::Black);FEditableTextBoxStyle S=I->GetWidgetStyle();S.SetForegroundColor(Black).SetFocusedForegroundColor(Black).SetReadOnlyForegroundColor(Black);FTextBlockStyle T=S.TextStyle;T.SetColorAndOpacity(Black);S.SetTextStyle(T);I->SetWidgetStyle(S);}}
UIdolQuizRoomWidget::UIdolQuizRoomWidget(const FObjectInitializer& ObjectInitializer):Super(ObjectInitializer){SetIsFocusable(true);}
TSharedRef<SWidget>UIdolQuizRoomWidget::RebuildWidget(){if(WidgetTree&&!WidgetTree->RootWidget)BuildLayout();return Super::RebuildWidget();}
void UIdolQuizRoomWidget::BuildLayout(){UCanvasPanel* R=WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(),TEXT("RoomRoot"));WidgetTree->RootWidget=R;auto Add=[R](UWidget* W,float X,float Y,FVector2D S){UCanvasPanelSlot* P=R->AddChildToCanvas(W);P->SetAnchors(FAnchors(X,Y));P->SetAlignment(FVector2D(.5f,.5f));P->SetSize(S);};UImage* BG=WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(),TEXT("BG"));BG->SetColorAndOpacity(FLinearColor(.005f,.012f,.035f,1));UCanvasPanelSlot* BS=R->AddChildToCanvas(BG);BS->SetAnchors(FAnchors(0,0,1,1));BS->SetOffsets(FMargin(0));Add(Txt(WidgetTree,TEXT("Title"),TEXT("퀴즈 방 목록"),44),.5f,.07f,{700,70});UButton* Create=Btn(WidgetTree,TEXT("OpenCreate"),TEXT("방 만들기"),22);Create->OnClicked.AddDynamic(this,&ThisClass::OpenCreateDialog);Add(Create,.38f,.17f,{230,58});UButton* Refresh=Btn(WidgetTree,TEXT("Refresh"),TEXT("새로고침"),22);Refresh->OnClicked.AddDynamic(this,&ThisClass::HandleRefresh);Add(Refresh,.62f,.17f,{230,58});for(int32 I=0;I<6;++I){UButton* B=Btn(WidgetTree,*FString::Printf(TEXT("Room%d"),I),TEXT(""),19);UTextBlock* L=Cast<UTextBlock>(B->GetChildAt(0));B->SetVisibility(ESlateVisibility::Collapsed);Add(B,.5f,.28f+I*.085f,{980,62});RoomButtons.Add(B);RoomLabels.Add(L);}RoomButtons[0]->OnClicked.AddDynamic(this,&ThisClass::Join0);RoomButtons[1]->OnClicked.AddDynamic(this,&ThisClass::Join1);RoomButtons[2]->OnClicked.AddDynamic(this,&ThisClass::Join2);RoomButtons[3]->OnClicked.AddDynamic(this,&ThisClass::Join3);RoomButtons[4]->OnClicked.AddDynamic(this,&ThisClass::Join4);RoomButtons[5]->OnClicked.AddDynamic(this,&ThisClass::Join5);StatusText=Txt(WidgetTree,TEXT("Status"),TEXT("방을 찾는 중..."),18);Add(StatusText,.5f,.84f,{900,45});UButton* Back=Btn(WidgetTree,TEXT("Back"),TEXT("ALL GAMES"),20);Back->OnClicked.AddDynamic(this,&ThisClass::HandleMainHub);Add(Back,.1f,.94f,{190,52});
	CreateDialog=WidgetTree->ConstructWidget<UCanvasPanel>(UCanvasPanel::StaticClass(),TEXT("CreateRoomDialog"));Add(CreateDialog,.5f,.5f,{650,430});auto D=[this](UWidget* W,float X,float Y,FVector2D S){UCanvasPanelSlot* P=CreateDialog->AddChildToCanvas(W);P->SetPosition({X,Y});P->SetSize(S);};UImage* Panel=WidgetTree->ConstructWidget<UImage>(UImage::StaticClass(),TEXT("DialogBackground"));Panel->SetColorAndOpacity(FLinearColor(.025f,.045f,.1f,.98f));D(Panel,0,0,{650,430});D(Txt(WidgetTree,TEXT("DialogTitle"),TEXT("방 만들기"),32),75,28,{500,55});D(Txt(WidgetTree,TEXT("NameLabel"),TEXT("방 제목"),19),45,105,{120,45});RoomNameInput=WidgetTree->ConstructWidget<UEditableTextBox>(UEditableTextBox::StaticClass(),TEXT("RoomNameInput"));RoomNameInput->SetHintText(FText::FromString(TEXT("방 제목을 입력하세요")));BlackInput(RoomNameInput);D(RoomNameInput,175,105,{420,48});D(Txt(WidgetTree,TEXT("CategoryLabel"),TEXT("출제 범위"),19),45,175,{120,45});CategoryDropdown=WidgetTree->ConstructWidget<UComboBoxString>(UComboBoxString::StaticClass(),TEXT("CategoryDropdown"));CategoryDropdown->AddOption(TEXT("아이돌"));CategoryDropdown->AddOption(TEXT("배우"));CategoryDropdown->AddOption(TEXT("아이돌 + 배우"));CategoryDropdown->SetSelectedIndex(0);CategoryDropdown->OnSelectionChanged.AddDynamic(this,&ThisClass::HandleCategoryChanged);D(CategoryDropdown,175,175,{420,48});DialogErrorText=Txt(WidgetTree,TEXT("DialogError"),TEXT(""),17);DialogErrorText->SetColorAndOpacity(FSlateColor(FLinearColor(1,.3f,.3f)));D(DialogErrorText,75,235,{500,38});UButton* Confirm=Btn(WidgetTree,TEXT("ConfirmCreate"),TEXT("만들기"),21);Confirm->OnClicked.AddDynamic(this,&ThisClass::ConfirmCreateRoom);D(Confirm,335,310,{220,58});UButton* Cancel=Btn(WidgetTree,TEXT("CancelCreate"),TEXT("취소"),21);Cancel->OnClicked.AddDynamic(this,&ThisClass::CloseCreateDialog);D(Cancel,95,310,{200,58});CreateDialog->SetVisibility(ESlateVisibility::Collapsed);}
void UIdolQuizRoomWidget::NativeConstruct(){Super::NativeConstruct();Sessions=GetGameInstance()?GetGameInstance()->GetSubsystem<UIdolQuizSessionSubsystem>():nullptr;if(Sessions){Sessions->OnRoomsFound.AddUObject(this,&ThisClass::HandleRoomsFound);Sessions->OnSessionAction.AddUObject(this,&ThisClass::HandleSessionAction);Sessions->FindRooms();}}
void UIdolQuizRoomWidget::NativeDestruct(){if(Sessions){Sessions->OnRoomsFound.RemoveAll(this);Sessions->OnSessionAction.RemoveAll(this);}Super::NativeDestruct();}
void UIdolQuizRoomWidget::OpenCreateDialog(){RoomNameInput->SetText(FText::GetEmpty());CategoryDropdown->SetSelectedIndex(0);SelectedCategory=EIdolQuizRoomCategory::Idol;DialogErrorText->SetText(FText::GetEmpty());CreateDialog->SetVisibility(ESlateVisibility::Visible);RoomNameInput->SetKeyboardFocus();}
void UIdolQuizRoomWidget::CloseCreateDialog(){CreateDialog->SetVisibility(ESlateVisibility::Collapsed);}
void UIdolQuizRoomWidget::HandleCategoryChanged(FString Item,ESelectInfo::Type){SelectedCategory=Item==TEXT("배우")?EIdolQuizRoomCategory::Actor:Item==TEXT("아이돌 + 배우")?EIdolQuizRoomCategory::IdolAndActor:EIdolQuizRoomCategory::Idol;}
void UIdolQuizRoomWidget::ConfirmCreateRoom(){const FString Name=RoomNameInput->GetText().ToString().TrimStartAndEnd();if(Name.IsEmpty()){DialogErrorText->SetText(FText::FromString(TEXT("방 제목을 입력해 주세요.")));return;}if(Sessions){CloseCreateDialog();StatusText->SetText(FText::FromString(TEXT("방을 만드는 중...")));Sessions->CreateRoom(Name,SelectedCategory);}}
void UIdolQuizRoomWidget::HandleRefresh(){if(Sessions){StatusText->SetText(FText::FromString(TEXT("방을 빠르게 검색 중...")));Sessions->FindRooms();}}
void UIdolQuizRoomWidget::HandleRoomsFound(bool b,const TArray<FIdolQuizRoomInfo>& Rooms){for(UButton* B:RoomButtons)B->SetVisibility(ESlateVisibility::Collapsed);for(int32 I=0;I<FMath::Min(Rooms.Num(),RoomButtons.Num());++I){RoomLabels[I]->SetText(FText::FromString(FString::Printf(TEXT("%s    [%s]    %d / %d    %d ms"),*Rooms[I].RoomName,*UIdolQuizSessionSubsystem::GetCategoryLabel(Rooms[I].Category),Rooms[I].CurrentPlayers,Rooms[I].MaxPlayers,Rooms[I].PingMs)));RoomButtons[I]->SetVisibility(ESlateVisibility::Visible);}StatusText->SetText(FText::FromString(!b?TEXT("방 검색에 실패했습니다."):Rooms.IsEmpty()?TEXT("참가 가능한 방이 없습니다."):FString::Printf(TEXT("%d개의 방을 찾았습니다."),Rooms.Num())));}
void UIdolQuizRoomWidget::HandleSessionAction(bool b,const FString& M){StatusText->SetColorAndOpacity(FSlateColor(b?FLinearColor(.3f,1,.5f):FLinearColor(1,.3f,.3f)));StatusText->SetText(FText::FromString(M));}
void UIdolQuizRoomWidget::JoinIndex(int32 I){if(Sessions)Sessions->JoinRoom(I);}void UIdolQuizRoomWidget::Join0(){JoinIndex(0);}void UIdolQuizRoomWidget::Join1(){JoinIndex(1);}void UIdolQuizRoomWidget::Join2(){JoinIndex(2);}void UIdolQuizRoomWidget::Join3(){JoinIndex(3);}void UIdolQuizRoomWidget::Join4(){JoinIndex(4);}void UIdolQuizRoomWidget::Join5(){JoinIndex(5);}void UIdolQuizRoomWidget::HandleMainHub(){UGameplayStatics::OpenLevel(this,TEXT("MainHubMap"));}
