#include "DrawingQuizGameMode.h"
#include "DrawingQuizGameState.h"
#include "DrawingQuizPlayerController.h"
#include "DrawingQuizPlayerState.h"
#include "../Online/IdolQuizSessionSubsystem.h"
#include "TimerManager.h"

ADrawingQuizGameMode::ADrawingQuizGameMode(){DefaultPawnClass=nullptr;PlayerControllerClass=ADrawingQuizPlayerController::StaticClass();PlayerStateClass=ADrawingQuizPlayerState::StaticClass();GameStateClass=ADrawingQuizGameState::StaticClass();bUseSeamlessTravel=true;BuildWordPool();}
void ADrawingQuizGameMode::BeginPlay(){Super::BeginPlay();if(UGameInstance* GI=GetGameInstance())if(UIdolQuizSessionSubsystem* Sessions=GI->GetSubsystem<UIdolQuizSessionSubsystem>()){RoundsPerPlayer=Sessions->GetActiveDrawingRoundsPerPlayer();RoundDurationSeconds=Sessions->GetActiveDrawingRoundTime();}UE_LOG(LogTemp,Log,TEXT("Drawing Quiz configured: %d rounds per player, %d seconds"),RoundsPerPlayer,RoundDurationSeconds);GetWorldTimerManager().SetTimer(StartTimer,this,&ThisClass::StartNextRound,2.f,false);}
void ADrawingQuizGameMode::BuildWordPool(){Words={TEXT("사과"),TEXT("고양이"),TEXT("우산"),TEXT("비행기"),TEXT("피아노"),TEXT("눈사람"),TEXT("자전거"),TEXT("햄버거"),TEXT("소방차"),TEXT("무지개"),TEXT("선풍기"),TEXT("거북이"),TEXT("축구공"),TEXT("딸기"),TEXT("로봇"),TEXT("해바라기"),TEXT("기린"),TEXT("컴퓨터"),TEXT("놀이공원"),TEXT("치약")};for(int32 I=Words.Num()-1;I>0;--I)Words.Swap(I,FMath::RandRange(0,I));}
FString ADrawingQuizGameMode::Normalize(const FString& Value)const{FString Result=Value.TrimStartAndEnd().ToLower();for(const TCHAR* S:{TEXT(" "),TEXT("\t"),TEXT("-"),TEXT("_")})Result.ReplaceInline(S,TEXT(""));return Result;}
FString ADrawingQuizGameMode::BuildHint(const FString& Word)const{FString Result;for(TCHAR C:Word)Result+=FChar::IsWhitespace(C)?TEXT(" "):TEXT("○");return Result;}
ADrawingQuizPlayerState* ADrawingQuizGameMode::GetDrawer()const{const AGameStateBase* GS=GetGameState<AGameStateBase>();return GS&&GS->PlayerArray.IsValidIndex(DrawerIndex)?Cast<ADrawingQuizPlayerState>(GS->PlayerArray[DrawerIndex]):nullptr;}
void ADrawingQuizGameMode::StartNextRound(){AGameStateBase* BaseState=GetGameState<AGameStateBase>();if(!BaseState||BaseState->PlayerArray.IsEmpty()){GetWorldTimerManager().SetTimer(StartTimer,this,&ThisClass::StartNextRound,1.f,false);return;}const int32 TotalRounds=BaseState->PlayerArray.Num()*RoundsPerPlayer;if(CurrentRound>=TotalRounds){FinishGame();return;}++CurrentRound;DrawerIndex=(CurrentRound-1)%BaseState->PlayerArray.Num();CurrentWordIndex=(CurrentWordIndex+1)%Words.Num();CurrentWord=Words[CurrentWordIndex];RemainingSeconds=RoundDurationSeconds;bRoundResolved=false;for(APlayerState* PS:BaseState->PlayerArray)if(ADrawingQuizPlayerState* DrawingPS=Cast<ADrawingQuizPlayerState>(PS))DrawingPS->SetSolvedCurrentRound(false);ADrawingQuizPlayerState* Drawer=GetDrawer();if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>()){GS->ClearCanvasState();GS->SetRoundState(CurrentRound,TotalRounds,Drawer,RemainingSeconds,BuildHint(CurrentWord));}for(FConstPlayerControllerIterator It=GetWorld()->GetPlayerControllerIterator();It;++It)if(ADrawingQuizPlayerController* PC=Cast<ADrawingQuizPlayerController>(It->Get()))PC->ClientSetSecretWord(PC->PlayerState==Drawer?CurrentWord:FString());GetWorldTimerManager().SetTimer(RoundTimer,this,&ThisClass::TickRound,1.f,true);}
void ADrawingQuizGameMode::TickRound(){if(bRoundResolved)return;RemainingSeconds=FMath::Max(0,RemainingSeconds-1);if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>())GS->SetRemainingTime(RemainingSeconds);if(RemainingSeconds<=0)ResolveRound(FString::Printf(TEXT("시간 초과! 정답: %s"),*CurrentWord));}
void ADrawingQuizGameMode::SubmitChat(ADrawingQuizPlayerController* Sender,const FString& Message){if(!Sender||Message.TrimStartAndEnd().IsEmpty())return;ADrawingQuizPlayerState* SenderState=Sender->GetPlayerState<ADrawingQuizPlayerState>();if(!SenderState)return;if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>())GS->MulticastChat(SenderState->GetQuizName(),Message.TrimStartAndEnd().Left(80),SenderState->GetPlayerColorIndex());if(bRoundResolved||SenderState==GetDrawer()||SenderState->HasSolvedCurrentRound()||Normalize(Message)!=Normalize(CurrentWord))return;SenderState->SetSolvedCurrentRound(true);SenderState->AddScore(100+RemainingSeconds*5);if(ADrawingQuizPlayerState* Drawer=GetDrawer())Drawer->AddScore(100);ResolveRound(FString::Printf(TEXT("%s 정답! %s"),*SenderState->GetQuizName(),*CurrentWord));}
void ADrawingQuizGameMode::SubmitStrokes(ADrawingQuizPlayerController* Sender,const TArray<FDrawingQuizStrokeSegment>& Segments){if(!Sender||bRoundResolved||Sender->PlayerState!=GetDrawer()||Segments.IsEmpty())return;TArray<FDrawingQuizStrokeSegment> SafeSegments;SafeSegments.Reserve(FMath::Min(Segments.Num(),64));for(int32 Index=0;Index<Segments.Num()&&Index<64;++Index){FDrawingQuizStrokeSegment Safe=Segments[Index];Safe.Start.X=FMath::Clamp(Safe.Start.X,0.f,1.f);Safe.Start.Y=FMath::Clamp(Safe.Start.Y,0.f,1.f);Safe.End.X=FMath::Clamp(Safe.End.X,0.f,1.f);Safe.End.Y=FMath::Clamp(Safe.End.Y,0.f,1.f);Safe.Thickness=FMath::Clamp(Safe.Thickness,2.f,40.f);SafeSegments.Add(Safe);}if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>())GS->MulticastStrokes(SafeSegments);}
void ADrawingQuizGameMode::ClearCanvas(ADrawingQuizPlayerController* Sender){if(!Sender||Sender->PlayerState!=GetDrawer()){UE_LOG(LogTemp,Warning,TEXT("Drawing Quiz clear rejected: sender is not the drawer."));return;}if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>()){GS->ClearCanvasState();UE_LOG(LogTemp,Log,TEXT("Drawing Quiz canvas cleared by drawer."));}}
void ADrawingQuizGameMode::ResolveRound(const FString& Feedback){if(bRoundResolved)return;bRoundResolved=true;GetWorldTimerManager().ClearTimer(RoundTimer);if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>())GS->SetFeedback(Feedback);for(FConstPlayerControllerIterator It=GetWorld()->GetPlayerControllerIterator();It;++It)if(ADrawingQuizPlayerController* PC=Cast<ADrawingQuizPlayerController>(It->Get()))PC->ClientSetSecretWord(CurrentWord);GetWorldTimerManager().SetTimer(AdvanceTimer,this,&ThisClass::StartNextRound,3.f,false);}
void ADrawingQuizGameMode::FinishGame(){if(ADrawingQuizGameState* GS=GetGameState<ADrawingQuizGameState>()){GS->SetFeedback(TEXT("게임 종료"));GS->SetFinished(true);}}
